const mongoose = require('mongoose');

const wasteRequestSchema = new mongoose.Schema({
  // Generated by facility after collection
  trackingId: { type: String, unique: true, sparse: true },

  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  facility: { type: mongoose.Schema.Types.ObjectId, ref: 'Facility', required: true },

  wasteItems: [{
    category: {
      type: String,
      enum: [
        'mobile_phones', 'laptops', 'computers', 'televisions',
        'refrigerators', 'washing_machines', 'air_conditioners',
        'batteries', 'printers', 'tablets', 'cameras',
        'audio_equipment', 'cables_accessories', 'other'
      ],
      required: true
    },
    description: String,
    estimatedWeight: Number, // in kg
    actualWeight: Number,    // filled by recycler
    brand: String,
    model: String,
    condition: { type: String, enum: ['working', 'not_working', 'damaged', 'unknown'], default: 'unknown' }
  }],

  wasteCategory: {
    type: String,
    enum: ['small', 'bulk'],
    required: true
    // small = drop-off (individual), bulk = pickup (company or large qty)
  },

  serviceType: {
    type: String,
    enum: ['drop_off', 'pickup'],
    required: true
  },

  // Pickup details (only for bulk)
  pickupAddress: {
    street: String,
    city: String,
    state: String,
    pincode: String
  },
  pickupLocation: {
    type: { type: String, enum: ['Point'] },
    coordinates: [Number]
  },
  scheduledDate: Date,
  scheduledTime: String,

  // Status flow
  status: {
    type: String,
    enum: [
      'pending',        // submitted by user, awaiting facility
      'confirmed',      // facility confirmed the request
      'collected',      // dropped off or picked up
      'processing',     // being processed at facility
      'recycled',       // fully recycled
      'cancelled'
    ],
    default: 'pending'
  },

  // Compensation
  estimatedCompensation: { type: Number, default: 0 },
  finalCompensation: { type: Number, default: 0 },
  compensationStatus: {
    type: String,
    enum: ['pending', 'verified', 'paid'],
    default: 'pending'
  },

  totalEstimatedWeight: { type: Number, default: 0 },
  totalActualWeight: { type: Number, default: 0 },

  // Notes
  userNotes: String,
  recyclerNotes: String,

  // Timestamps
  requestedAt: { type: Date, default: Date.now },
  confirmedAt: Date,
  collectedAt: Date,
  processingStartedAt: Date,
  recycledAt: Date,

  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now }
});

wasteRequestSchema.index({ pickupLocation: '2dsphere' });

wasteRequestSchema.pre('save', function (next) {
  this.updatedAt = Date.now();
  next();
});

module.exports = mongoose.model('WasteRequest', wasteRequestSchema);
